//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskWeb
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class tbRoleMenuButton
    {
        public int roleId { get; set; }
        public int menuId { get; set; }
        public int buttonId { get; set; }

        [JsonIgnore]
        public virtual tbButton tbButton { get; set; }
        [JsonIgnore]
        public virtual tbMenu tbMenu { get; set; }
        [JsonIgnore]
        public virtual tbRole tbRole { get; set; }
    }
}
