//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskWeb
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    
    public partial class tbTask
    {
        public tbTask()
        {
            this.tbTaskAssign = new HashSet<tbTaskAssign>();
            this.tbTaskProcess = new HashSet<tbTaskProcess>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public System.DateTime startTime { get; set; }
        public System.DateTime endTime { get; set; }
        public int status { get; set; }
        public int type { get; set; }
        public int kind { get; set; }
        public int rating { get; set; }
        public string condition { get; set; }
        public int points { get; set; }
        public System.DateTime addTime { get; set; }
        public int creatorId { get; set; }
        public string result { get; set; }

        [JsonIgnore]
        public virtual tbUser tbUser { get; set; }
        public virtual ICollection<tbTaskAssign> tbTaskAssign { get; set; }
        public virtual ICollection<tbTaskProcess> tbTaskProcess { get; set; }
    }
}
