//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserOperateLog
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string userIp { get; set; }
        public string operateInfo { get; set; }
        public string description { get; set; }
        public Nullable<bool> ifSuccess { get; set; }
        public System.DateTime operateDate { get; set; }
    }
}
